### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by savormix** [Romanito/SimFlightPath-Issues#1]
Steps to reproduce the bug:
- Crash during a bush trip

Error details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SimFlightPath.Formats.Gpx.EndFlight(FlightMetadata flightMetadata) in SimFlightPath\Formats\Gpx.cs:line 118
   at SimFlightPath.Model.FlightLogger.EndLog() in SimFlightPath\Model\FlightLogger.cs:line 281
   at SimFlightPath.Model.FlightLogger.SimConnectHelper_DataReceived(Object sender, DataReceivedEventArgs e) in SimFlightPath\Model\FlightLogger.cs:line 87
   at SimFlightPath.Model.SimConnectHelper.OnRecvSimobjectData(SimConnect sender, SIMCONNECT_RECV_SIMOBJECT_DATA data) in SimFlightPath\Model\SimConnectHelper.cs:line 303
   at Microsoft.FlightSimulator.SimConnect.SimConnect.OnReceiveMessage(SIMCONNECT_RECV pData, UInt32 cbData)
   at SimConnect_CallDispatch(Void* , IntPtr , Void* )
   at Microsoft.FlightSimulator.SimConnect.SimConnect.ReceiveDispatch(SignalProcDelegate pfcnSignal)
   at SimFlightPath.Model.SimConnectHelper.MessageReceiverWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in SimFlightPath\Model\SimConnectHelper.cs:line 340
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Romanito** [comment]
Thanks for the bug report.
This has been fixed in SimFlightPath 1.6.
