### ISSUE TITLE
FileSystemWatcher creation fails if the LogFilesPath folder isn't accessible

### ISSUE THREAD

**Issue by dariokavalkeviski** [Romanito/SimFlightPath-Issues#11]
Steps to reproduce the bug:
- 

Error details:
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'SimFlightPath.ViewModel.MainViewModel' that matches the specified binding constraints threw an exception.
 ---> System.ArgumentException: The directory name 'C:\Users\Dario\AppData\Local\SimFlightPath\Flights' does not exist. (Parameter 'path')
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at SimFlightPath.Model.LogFiles.Initialize() in SimFlightPath\Model\LogFiles.cs:line 55
   at SimFlightPath.Model.LogFiles..ctor() in SimFlightPath\Model\LogFiles.cs:line 49
   at SimFlightPath.Model.LogFiles.get_Instance() in SimFlightPath\Model\LogFiles.cs:line 31
   at SimFlightPath.ViewModel.MainViewModel..ctor() in SimFlightPath\ViewModel\MainViewModel.cs:line 98
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.Application.FindResource(Object resourceKey)
   at SimFlightPath.App.OnStartup(StartupEventArgs e) in SimFlightPath\App.xaml.cs:line 77
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Romanito** [comment]
Hi Dario, sorry for the late answer. 
According to the error details the flight files should be saved in the **C:\Users\Dario\AppData\Local\SimFlightPath\Flights** folder.
Does this folder still exist? You can try creating it to temporarily allow SimFlighPath to launch and change the flights path setting.

If this doesn't fix the problem, you can try to reset SimFlightPath user settings:
1. In Windows Explorer, navigate to **%localappdata%\SimFlightPath**.
2. There should be a folder whose name starts with **SimFlightPath_Url_**. If there is more than one, use the most recent one.
3. In this folder, open the subfolder with the highest version number.
4. Rename the **user.config** file or open it with a text editor and delete the value of the **LogFilesPath** setting.

I'll keep this issue open as a reminder to handle this error more gracefully.
