### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by caduguimaraes** [Romanito/SimFlightPath-Issues#2]
Steps to reproduce the bug:
- 

Error details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SimFlightPath.ViewModel.FlightViewModel.SetProperties() in SimFlightPath\ViewModel\FlightViewModel.cs:line 258
   at SimFlightPath.ViewModel.FlightViewModel.set_Metadata(FlightMetadata value) in SimFlightPath\ViewModel\FlightViewModel.cs:line 91
   at SimFlightPath.ViewModel.FlightViewModel..ctor(FlightMetadata flightMetadata) in SimFlightPath\ViewModel\FlightViewModel.cs:line 115
   at SimFlightPath.Formats.Gpx.EndFlight(FlightMetadata flightMetadata) in SimFlightPath\Formats\Gpx.cs:line 99
   at SimFlightPath.Model.FlightLogger.EndLog() in SimFlightPath\Model\FlightLogger.cs:line 296
   at SimFlightPath.Model.FlightLogger.SimConnectHelper_DataReceived(Object sender, DataReceivedEventArgs e) in SimFlightPath\Model\FlightLogger.cs:line 91
   at SimFlightPath.Model.SimConnectHelper.OnRecvSimobjectData(SimConnect sender, SIMCONNECT_RECV_SIMOBJECT_DATA data) in SimFlightPath\Model\SimConnectHelper.cs:line 305
   at Microsoft.FlightSimulator.SimConnect.SimConnect.OnReceiveMessage(SIMCONNECT_RECV pData, UInt32 cbData)
   at SimConnect_CallDispatch(Void* , IntPtr , Void* )
   at Microsoft.FlightSimulator.SimConnect.SimConnect.ReceiveDispatch(SignalProcDelegate pfcnSignal)
   at SimFlightPath.Model.SimConnectHelper.MessageReceiverWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in SimFlightPath\Model\SimConnectHelper.cs:line 342
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Romanito** [comment]
This should be fixed in version 1.7
