### ISSUE TITLE
DirectoryNotFoundException: Could not find a part of the path 'C:\Users\crazy\AppData\Local\SimFlightPath\Temp\2022-05-19 13-19 [FR-0182-LFRB].kml'.

### ISSUE THREAD

**Issue by mayerbalint** [Romanito/SimFlightPath-Issues#6]
Steps to reproduce the bug:
- 

Error details:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\crazy\AppData\Local\SimFlightPath\Temp\2022-05-19 13-19 [FR-0182-LFRB].kml'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at SimFlightPath.Formats.Kml.GpxToKml(String sourceFileName, String destFileName, Boolean twoD) in SimFlightPath\Formats\Kml.cs:line 284
   at SimFlightPath.ViewModel.FlightViewModel.ExecuteOpenFile(Object parameter) in SimFlightPath\ViewModel\FlightViewModel.cs:line 264
   at SimFlightPath.RelayCommand.Execute(Object parameter) in SimFlightPath\Core\RelayCommand.cs:line 25
   at SimFlightPath.View.FlightsView.lbFiles_MouseDoubleClick(Object sender, MouseButtonEventArgs e) in SimFlightPath\View\FlightsView.xaml.cs:line 134
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Control.OnMouseDoubleClick(MouseButtonEventArgs e)
   at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Romanito** [comment]
The fix for this error has been published in SimFlightPath 1.8
